name: Azure Function deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:windows-latest
    steps:
     - name: Checkout repository
       uses: actions/setup-node@v1
       with:
         node-version: '18.x'
          
     - name: Setup Nodejs
       uses: actions/setup-node@v1
       with:
         node-version: '18.x'
          
     - name: Install dependencies
       run:: npm install
        
     - name: Deploy to Azure Function App
       uses: azure/functions-action@v1
       with:
         app-name: 'manunivfunc'
         package: .
         publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
